name: win-test

on:
  push:
    tags:
    - 'v*'

  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: clear

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
        with:
            msbuild-architecture: x64

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'
          vcpkgGitCommitId: 'a194ab0156b30469ce5034ceb8e83c1531f7deba'

      - name: Install dependencies
        working-directory: ${{runner.workspace}}/windeploynunchuk
        run: |
          & "$env:VCPKG_ROOT\vcpkg" install

