name: win

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore from cache and install vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: 'boost libevent qt5 qt5-graphicaleffects qt5-quickcontrols'
          vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
          vcpkgTriplet: 'x64-windows'
          vcpkgGitCommitId: '539a182d3773b9a84807b978c9684ba471446bf4'

